app:
    resource: "@AppBundle/Controller/"
    type:     annotation

vendor_sonata:
    resource: custom/routing_sonata.yml

vendor_cmf:
    resource: custom/routing_cmf.yml

vendor_other:
    resource: custom/routing_others.yml


