# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    user.provider.oauth:
        class: AppBundle\Security\Provider\OAuthUserProvider
        arguments: ['@fos_user.user_manager',{facebook: facebookID, google: googleID}]

    fos_user.entity_manager:
        alias: fos_user.object_manager

    app.h5p_framework:
        class: AppBundle\Service\H5P\AppH5PFramework
        arguments: ['@service_container']

#    app.h5p_editor_storage:
#        class: AppBundle\Service\H5P\AppH5PEditorStorage
#        arguments: ['@service_container']
#    app.h5p_editor_ajax:
#        class: AppBundle\Service\H5P\AppH5PEditorAjax
#        arguments: ['@service_container']
#    app.h5p_editor:
#        class: H5peditor
#        arguments: ['@app.h5p','@app.h5p_editor_storage','@app.h5p_editor_ajax']

    app.twig:
        class: AppBundle\Twig\AppExtension
        arguments: ['@router.default','@app.site','@request_stack']
        tags:
            - {name: 'twig.extension'}

    app.pagerfanta.view.default:
        class: AppBundle\Service\Pagerfanta\AppView
        public: false
        tags: [{ name: pagerfanta.view, alias: app_pagerfanta_view_default }]


    app.h5p:
        class: AppBundle\Service\H5P\H5PService
        arguments: ['@service_container', '@app.h5p_framework']

    app.user:
        class: AppBundle\Service\User\UserService
        arguments:
            - "@service_container"

    app.site:
        class: AppBundle\Service\SiteService
        arguments:
            - "@service_container"

    app.admin.security.handler.role:
        class: AppBundle\Admin\Security\Handler\RoleSecurityHandler
        arguments: ['@security.authorization_checker', ['ROLE_ADMIN'], '@service_container']


############################
    app.string:
        class: AppBundle\Service\StringService
        arguments:
            - "@service_container"

    app.excel:
        class: AppBundle\Service\ExcelService
        arguments:
            - "@service_container"

    app.shortcode_factory:
        class: AppBundle\Entity\Content\NodeShortcode\ShortcodeFactory
        arguments:
            - "@service_container"
################# Security Menu Builder
    app.admin.security.menu_listener_teacher:
        class: AppBundle\Admin\Security\MenuBuilderListener\TeacherRoleMBListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    app.admin.security.menu_listener_huynhtruong:
        class: AppBundle\Admin\Security\MenuBuilderListener\HuynhTruongRoleMBListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
