services:
    app_binhle__thieunhi__thanhvien__doctrine_entity_listener:
        class: AppBundle\Doctrine\ORM\Listener\BinhLe\ThieuNhi\ThanhVienListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }

    app_binhle__thieunhi__phanbo__doctrine_entity_listener:
        class: AppBundle\Doctrine\ORM\Listener\BinhLe\ThieuNhi\PhanBoListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                entity_listeners:
                    entities:
                        -
                            class:  "AppBundle\\Entity\\BinhLe\\ThieuNhi\\ThanhVien"
                            listener:
                                -
                                    class: "AppBundle\\Doctrine\\ORM\\Listener\\BinhLe\\ThieuNhi\\ThanhVienListener"
                                    event:
                                        -
                                            type: postPersist
                                            method: postPersistHandler
                                        -
                                            type: postUpdate
                                            method: postUpdateHandler
                                        -
                                            type: prePersist
                                            method: prePersistHandler
                                        -
                                            type: preUpdate
                                            method: preUpdateHandler
                                        -
                                            type: preRemove
                                            method: preRemoveHandler
                                        -
                                            type: postRemove
                                            method: postRemoveHandler

                        -
                            class:  "AppBundle\\Entity\\BinhLe\\ThieuNhi\\PhanBo"
                            listener:
                                -
                                    class: "AppBundle\\Doctrine\\ORM\\Listener\\BinhLe\\ThieuNhi\\PhanBoListener"
                                    event:
                                        -
                                            type: postPersist
                                            method: postPersistHandler
                                        -
                                            type: postUpdate
                                            method: postUpdateHandler
                                        -
                                            type: prePersist
                                            method: prePersistHandler
                                        -
                                            type: preUpdate
                                            method: preUpdateHandler
                                        -
                                            type: preRemove
                                            method: preRemoveHandler
                                        -
                                            type: postRemove
                                            method: postRemoveHandler
