services:
    app.admin.binhle_thieunhi_thanhvien:
        class: AppBundle\Admin\BinhLe\ThieuNhi\ThanhVienAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\ThanhVien, AppBundle:Admin/BinhLe/ThieuNhi/ThanhVienAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_thanhvien, group: binhle, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_huynhtruong:
        class: AppBundle\Admin\BinhLe\ThieuNhi\HuynhTruongAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\ThanhVien, AppBundle:Admin/BinhLe/ThieuNhi/HuynhTruongAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_huynhtruong, group: binhle, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_phandoantruong_chidoan:
        class: AppBundle\Admin\BinhLe\ThieuNhi\PhanDoanTruongChiDoanAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\ChiDoan, AppBundle:Admin/BinhLe/ThieuNhi/PhanDoanTruongChiDoanAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_phandoantruong_chidoan, show_in_dashboard: false, label_translator_strategy: sonata.admin.label.strategy.underscore }


    app.admin.binhle_thieunhi_tv_truongphutrachdoi:
        class: AppBundle\Admin\BinhLe\ThieuNhi\TVTruongPhuTrachDoiAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\PhanBo, AppBundle:Admin/BinhLe/ThieuNhi/TVTruongPhuTrachDoiAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_tv_truongphutrachdoi, show_in_dashboard: false, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_phanbo:
        class: AppBundle\Admin\BinhLe\ThieuNhi\PhanBoAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\PhanBo, AppBundle:Admin/BinhLe/ThieuNhi/PhanBoAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_phanbo, group: binhle, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_bangdiem:
        class: AppBundle\Admin\BinhLe\ThieuNhi\BangDiemAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\BangDiem, AppBundle:Admin/BinhLe/ThieuNhi/BangDiemAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_bangdiem, group: binhle, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_chidoan:
        class: AppBundle\Admin\BinhLe\ThieuNhi\ChiDoanAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\ChiDoan, AppBundle:Admin/BinhLe/ThieuNhi/ChiDoanAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_chidoan, group: binhle, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_doinhomgiaoly:
        class: AppBundle\Admin\BinhLe\ThieuNhi\DoiNhomGiaoLyAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\DoiNhomGiaoLy, AppBundle:Admin/BinhLe/ThieuNhi/DoiNhomGiaoLyAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_doinhomgiaoly, group: binhle, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_truongphutrachdoi:
        class: AppBundle\Admin\BinhLe\ThieuNhi\TruongPhuTrachDoiAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\TruongPhuTrachDoi, AppBundle:Admin/BinhLe/ThieuNhi/TruongPhuTrachDoiAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_truongphutrachdoi, show_in_dashboard: false, label_translator_strategy: sonata.admin.label.strategy.underscore }

    app.admin.binhle_thieunhi_namhoc:
        class: AppBundle\Admin\BinhLe\ThieuNhi\NamHocAdmin
        arguments: [~, AppBundle\Entity\BinhLe\ThieuNhi\NamHoc, AppBundle:Admin/BinhLe/ThieuNhi/NamHocAdmin]
        calls:
#            - [setRouteBuilder,['@sonata.admin.route.path_info_slashes']]
            - [setIvoryCkeditor,['default']]
#            - [setStringService, ['@bean_core.string']]
#            - [setPHPCRService, ['@app.phpcr']]
#            - [addChild, ['@app.admin.product_clinics']]
            - [setTranslationDomain, ['BinhLeAdmin']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.binhle_thieunhi_namhoc, group: binhle, label_translator_strategy: sonata.admin.label.strategy.underscore }




