<?php
namespace Application\Bean\LocationBundle\Entity;

use Bean\Bundle\LocationBundle\Model\Geolocation as GeolocationModel;
use Doctrine\Common\Collections\ArrayCollection;
use JMS\Serializer\Annotation as Serializer;

class Geolocation extends GeolocationModel
{
    public function setAddress($address)
    {
        parent::setAddress($address); // TODO: Change the autogenerated stub
        if (empty($this->name)) {
            $this->name = $address;
        }
    }


    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }


}