<?php

namespace AppBundle\Entity\Notification;

use Sonata\NotificationBundle\Entity\BaseMessage as BaseMessage;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Message extends BaseMessage {
	/**
	 * @var int $id
	 */
	protected $id;
	
	/**
	 * Get id
	 *
	 * @return int $id
	 */
	public function getId() {
		return $this->id;
	}
}
